(format t "Verdadero y Falso~%")
(format t "~S~%" (and t nil))
(format t "Falso y Verdadero~%")
(format t "~S~%~%" (and nil t))
(format t "Esto nos recuerda al numero 0 en la multiplicacion~%")
(format t "1 x 0 = ~D~%" (* 1 0))
(format t "0 x 1 = ~D~%~%" (* 0 1))
(format t "Verdadero y Verdadero~%")
(format t "~S~%~%~%" (and t t))

(format t "Verdadero o Falso~%")
(format t "~S~%" (or t nil))
(format t "Falso o Verdadero~%")
(format t "~S~%~%" (or nil t))
(format t "Esto nos recuerda al numero 1 en la suma~%")
(format t "1 + 0 = ~D~%" (+ 0 1))
(format t "0 + 1 = ~D~%~%" (+ 1 0))
(format t "Falso o Falso~%")
(format t "~S~%~%~%" (or nil nil))

(if nil (format t "Esto nunca pasara~%") (format t "Porque nil evalua a falso~%"))
(if t (format t "Mientras t evalua a verdadero~%") (format t "Y esto nunca pasara~%"))

(if (or nil t) (format t "(or nil t) = t~%") (format t "(or nil t) = nil~%"))
(if (or t nil) (format t "(or t nil) = t~%") (format t "(or t nil) = nil~%"))
(if (or nil nil) (format t "(or nil nil) = t~%") (format t "(or nil nil) = nil~%"))
(if (or t t) (format t "(or t t) = t~%") (format t "(or t t) = nil~%"))

(if (and nil t)
    (format t "(and nil t) = t~%")
  (format t "(and nil t) = nil~%"))

(if (and t nil)
    (format t "(and t nil) = t~%")
  (format t "(and t nil) = nil~%"))
(if (and nil nil) (format t "(and nil nil) = t~%") (format t "(and nil nil) = nil~%"))
(if (and t t) (format t "(and t t) = t~%") (format t "(and t t) = nil~%"))
